package io.jingproject.common.anno;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

// marks a class as generated by an annotation processor.
// the source code of this class should never be manually modified.
// the generated class name should follow a specific naming convention,
// see io.jingproject.common.Utils#generateClassName for details
// on how the jing library generates the class name.
@Retention(RetentionPolicy.SOURCE)
@Target(ElementType.TYPE)
public @interface Generated {
}
