package io.jingproject.common.anno;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks a class as generated by an annotation processor.
 *
 * <p>This annotation indicates that the class has been automatically generated by an annotation processor.
 * The source code of this class should never be manually modified.</p>
 *
 * <p>The generated class name should follow a specific naming convention. You can refer to the {@link io.jingproject.common.Utils#generateClassName generateClassName}
 * method for details on how jing library generate the class name.</p>
 */
@Retention(RetentionPolicy.SOURCE)
@Target(ElementType.TYPE)
public @interface Generated {
}
